BEGIN
    DECLARE students AS DICTIONARY

    FUNCTION add_student()
        PRINT "Enter student name: "
        INPUT name
        PRINT "Enter student age: "
        INPUT age
        PRINT "Enter student marks: "
        INPUT marks
        SET students[name] TO {"age": age, "marks": marks}
        PRINT name + " added successfully!"

    FUNCTION show_students()
        IF students IS EMPTY THEN
            PRINT "No students found!"
            RETURN
        PRINT "Student Records:"
        FOR EACH name, data IN students
            PRINT "Name: " + name + ", Age: " + data["age"] + ", Marks: " + data["marks"]
    
    FUNCTION update_marks()
        PRINT "Enter student name to update marks: "
        INPUT name
        IF name EXISTS IN students THEN
            PRINT "Enter new marks: "
            INPUT new_marks
            SET students[name]["marks"] TO new_marks
            PRINT name + "'s marks updated!"
        ELSE
            PRINT "Student not found!"

    FUNCTION show_failed_students()
        PRINT "Students Who Failed:"
        FOR EACH name, data IN students
            IF data["marks"] < 40 THEN
                PRINT name + ": " + data["marks"]

    WHILE TRUE
        PRINT "1. Add Student"
        PRINT "2. Show Students"
        PRINT "3. Update Marks"
        PRINT "4. Show Failed Students"
        PRINT "5. Exit"
        
        PRINT "Choose an option: "
        INPUT choice

        IF choice == "1" THEN
            CALL add_student()
        ELSE IF choice == "2" THEN
            CALL show_students()
        ELSE IF choice == "3" THEN
            CALL update_marks()
        ELSE IF choice == "4" THEN
            CALL show_failed_students()
        ELSE IF choice == "5" THEN
            PRINT "Exiting..."
            BREAK
        ELSE
            PRINT "Invalid choice! Try again."

END

In [6]:
students = {}
def add_student():
    name = input("Enter student name: ")
    age = input("Enter student age: ")
    marks = input("Enter student marks: ")
    students[name] = {"age": age, "marks": marks}
    print(name + " added successfully!")

In [7]:
def show_students():
    if not students:
        print("No students found!")
        return
    print("Student Records:")
    for name, data in students.items():
        print("Name: " + name + ", Age: " + data["age"] + ", Marks: " + data["marks"])

In [8]:
def update_marks():
    name = input("Enter student name to update marks: ")
    if name in students:
        new_marks = input("Enter new marks: ")
        students[name]["marks"] = new_marks
        print(name + "'s marks updated!")
    else:
        print("Student not found!")

In [12]:

def show_failed_students():
    print("Students Who Failed:")
    for name, data in students.items():
        if data["marks"] < 40:
            print(name + ": " + data["marks"])

In [ ]:
while True:
    print("1. Add Student")
    print("2. Show Students")
    print("3. Update Marks")
    print("4. Show Failed Students")
    print("5. Exit")

    choice = input("Choose an option: ")

    if choice == "1":
        add_student()
    elif choice == "2":
        show_students()
    elif choice == "3":
        update_marks()
    elif choice == "4":
        show_failed_students()
    elif choice == "5":
        print("Exiting...")
        break
    else:
        print("Invalid choice! Try again.")